# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0cf78bdb59b67fb5f5155442fd9a7d02cced5d74a0b85595df4d0f89a60d5270d02330012f61064cfd88a7247005e38e6e47e9e373b0135e08c94fe25c1b198b
test:
  secret_key_base: 9e81f42af57f2df72e1bb035a947ebb254bfb46a71175e044666ce96fd542ba77f1f12191e8c2ee50adb89b7f5a325d8d912b0288a8f2bc57d292fb04df487ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_key: <%= ENV["GOOGLE_CLIENT_ID"] %>
  maps_key: <%= ENV["GOOGLE_MAPS_ID"] %>
